version: '2'

services:
    yang-php:
        container_name: yang-php
        image: php:8.2-cli
        volumes:
            - .:/var/www
        command: /bin/bash -c "cd /var/www; php vendor/bin/phpunit"
